# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

n1 = Neighborhood.create(name: "Richmond District")
n2 = Neighborhood.create(name: "Sunset District")
n3 = Neighborhood.create(name: "Presidio Heights")
n4 = Neighborhood.create(name: "Cole Valley")
n5 = Neighborhood.create(name: "Laurel Heights")
n6 = Neighborhood.create(name: "Lone Mountain")
n7 = Neighborhood.create(name: "Haight-Ashbury")
n8 = Neighborhood.create(name: "Marina District")
n9 = Neighborhood.create(name: "Cow Hollow")
n10 = Neighborhood.create(name: "Pacific Heights")
n11 = Neighborhood.create(name: "Nob Hill")
n12 = Neighborhood.create(name: "Telegraph Hill")
n13 = Neighborhood.create(name: "North Beach")
n14 = Neighborhood.create(name: "Russian Hill")
n15 = Neighborhood.create(name: "Financial District")
n16 = Neighborhood.create(name: "Chinatown")
n17 = Neighborhood.create(name: "Union Square")
n18 = Neighborhood.create(name: "Tenderloin")
n19 = Neighborhood.create(name: "Civic Center")
n20 = Neighborhood.create(name: "Western Addition")
n21 = Neighborhood.create(name: "Anza Vista")
n22 = Neighborhood.create(name: "Alamo Square")
n23 = Neighborhood.create(name: "NoPa (North of Panhandle)")
n24 = Neighborhood.create(name: "Lower Haight")
n25 = Neighborhood.create(name: "Hayes Valley")
n26 = Neighborhood.create(name: "Duboce Triangle")
n27 = Neighborhood.create(name: "Corona Heights")
n28 = Neighborhood.create(name: "Forest Knolls")
n29 = Neighborhood.create(name: "Golden Gate Heights")
n30 = Neighborhood.create(name: "Parkside")
n31 = Neighborhood.create(name: "Forest Hill")
n32 = Neighborhood.create(name: "Midtown Terrace")
n33 = Neighborhood.create(name: "Twin Peaks")
n34 = Neighborhood.create(name: "Upper Market")
n35 = Neighborhood.create(name: "Castro Disctrict")
n36 = Neighborhood.create(name: "Mission Dolores")
n37 = Neighborhood.create(name: "Mission District")
n39 = Neighborhood.create(name: "Potrero Hill")
n39 = Neighborhood.create(name: "Dogpatch")
n40 = Neighborhood.create(name: "Mission Bay")
n41 = Neighborhood.create(name: "SoMa (South of Market)")
n42 = Neighborhood.create(name: "Bayview - Hunter's Point")
n43 = Neighborhood.create(name: "Bernal Heights")
n44 = Neighborhood.create(name: "Noe Valley")
n45 = Neighborhood.create(name: "Glen Park")
n46 = Neighborhood.create(name: "Diamond Heights")
n47 = Neighborhood.create(name: "Miraloma Park")
n48 = Neighborhood.create(name: "West Portal")
n49 = Neighborhood.create(name: "Sherwood Forest")
n50 = Neighborhood.create(name: "St. Francis Wood")
n51 = Neighborhood.create(name: "Balboa Terrace")
n52 = Neighborhood.create(name: "Monterey Heights")
n53 = Neighborhood.create(name: "Westwood Highlands")
n54 = Neighborhood.create(name: "Mount Davidson Manor")
n55 = Neighborhood.create(name: "College Hill")
n56 = Neighborhood.create(name: "St. Mary's")
n57 = Neighborhood.create(name: "Portola District")
n57 = Neighborhood.create(name: "Excelsior District")
n58 = Neighborhood.create(name: "Sunnyside")
n59 = Neighborhood.create(name: "Mission Terrace")
n60 = Neighborhood.create(name: "Lakeshore")
n61 = Neighborhood.create(name: "Merced Heights")
n62 = Neighborhood.create(name: "ingleside Heights")
n63 = Neighborhood.create(name: "Ingleside Terrace")
n64 = Neighborhood.create(name: "Oceanview")
n65 = Neighborhood.create(name: "Outer Mission")
n66 = Neighborhood.create(name: "Crocker-Amazon")
n67 = Neighborhood.create(name: "Visitation Valley")
n68 = Neighborhood.create(name: "Little Hollywood")
